config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :l_users
  resources :products do
  	get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts  
    root 'store#index', as: 'store_index', via: :all
  end


  post '/line_items/:id/update_quantity' => 'line_items#update_quantity', as: 'line_items_update_quantity'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :line_items
	has_many :orders, through: :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

validates :title, :description, :image_url, presence: true
validates :title, uniqueness: true
validates :image_url, allow_blank: true, format: {
with:    %r{\.(gif|jpg|png)\Z}i,
message: 'must be a URL for GIF, JPG or PNG image.'
}
validates :price, numericality: { greater_than_or_equal_to: 0.01 }

private
# ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_line_item
		unless line_items.empty?
			errors.add(:base, 'Line Items present')
		throw :abort
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
        
        @products = Product.all
        ActionCable.server.broadcast 'products',
          html: render_to_string('store/index', layout: false)


      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    
    if stale?(@latest_order)
      respond_to do |format|
      format.atom
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_with(model: product, local: true) do |form|
  - if product.errors.any?
    #error_explanation
      %h2
        = pluralize(product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - product.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title, cols: 60
  .field
    = form.label :description
    = form.text_area :description, id: :product_description, rows: 10, cols: 60
  .field
    = form.label :image_url
    = form.text_field :image_url, cols: 60
  .field
    = form.label :price
    = form.text_field :price, cols: 60
  .actions
    = form.submit

app/views/products/edit.html.haml
%h1 Editing Product
= render 'form', product: @product
= link_to 'Show', @product
|
= link_to 'Back', products_path

app/views/products/index.html.haml
%body
  - if notice
    %aside#notice= notice
  %h1 Products
  %table
    %tfoot
      %tr
        %td{:colspan => "3"}
          = link_to 'New product', new_product_path
    %tbody
      - @products.each do |product|
        %tr{:class => "#{cycle('list_line_odd', 'list_line_even')}"}
          %td.image
            = image_tag(product.image_url, class: 'list_image')
          %td.description
            %h1= product.title
            %p
              = truncate(strip_tags(product.description), length: 80)
          %td.actions
            %ul
              %li= link_to 'Show', product
              %li= link_to 'Edit', edit_product_path(product)
              %li
                = link_to 'Destroy',                 |
                  product,                           |
                  method: :delete,                   |
                  data: { confirm: 'Are you sure?' } |

app/views/products/new.html.haml
%h1 New Product
= render 'form', product: @product
= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @product.title
%p
  %strong Description:
  = @product.description
%p
  %strong Image url:
  = @product.image_url
%p
  %strong Price:
  = @product.price
= link_to 'Edit', edit_product_path(@product)
|
= link_to 'Back', products_path