config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :l_users
  resources :products do
  	get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts  
    root 'store#index', as: 'store_index', via: :all
  end


  post '/line_items/:id/update_quantity' => 'line_items#update_quantity', as: 'line_items_update_quantity'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart

def total_price
	product.price * quantity
end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_action :authorize, only: :create
  
  include CurrentCart
  before_action :set_cart, only: [:create]

  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
  	product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
		format.html { redirect_to store_index_url }
		# format.js   { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end




  def update_quantity
    if @line_item = LineItem.find_by_id(params[:id])
      
      if params[:update_action] == 'increase'
   
        @line_item.quantity += 1
        @line_item.save
      
    elsif params[:update_action] == 'decrease'
        
      if @line_item.quantity > 1 
        @line_item.quantity -= 1
        @line_item.save
      else 
        @line_item.delete
      end
    
    elsif params[:update_action] == 'remove'
      
      @line_item.delete
      
    end
    
  end

    respond_to do |format|
        format.html { redirect_to store_index_url }
        # format.js { render :show, status: :created, location: @line_item }
    end
  end














  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.haml
= form_with(model: line_item, local: true) do |form|
  - if line_item.errors.any?
    #error_explanation
      %h2
        = pluralize(line_item.errors.count, "error")
        prohibited this line_item from being saved:
      %ul
        - line_item.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :product_id
    = form.text_field :product_id
  .field
    = form.label :cart_id
    = form.text_field :cart_id
  .actions
    = form.submit

app/views/line_items/_line_item.html.haml
- if line_item == @current_item
  %tr.line-item-highlight
- else
  %tr
    %td
      = button_to '-', line_items_update_quantity_path(line_item), method: :post,remote: true, params: {update_action: 'decrease'}
      %td= line_item.quantity
      %td= line_item.product.title
      %td.price= number_to_currency(line_item.total_price)
      %td= button_to '+', line_items_update_quantity_path(line_item), method: :post,remote: true, params: {update_action: 'increase'}
      %td= button_to 'x', line_items_update_quantity_path(line_item), method: :post,remote: true, params: {update_action: 'remove'}

app/views/line_items/_line_item.text.haml
= sprintf("%2d x %s",                            |
  line_item.quantity,                            |
  truncate(line_item.product.title, length: 50)) |

app/views/line_items/edit.html.haml
%h1 Editing Line Item
= render 'form', line_item: @line_item
= link_to 'Show', @line_item
|
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%p#notice= notice
%h1 Line Items
%table
  %thead
    %tr
      %th Product
      %th Cart
      %th{:colspan => "3"}
  %tbody
    - @line_items.each do |line_item|
      %tr
        %td= line_item.product
        %td= line_item.cart
        %td= link_to 'Show', line_item
        %td= link_to 'Edit', edit_line_item_path(line_item)
        %td= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Line Item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New Line Item
= render 'form', line_item: @line_item
= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice
%p
  %strong Product:
  = @line_item.product
%p
  %strong Cart:
  = @line_item.cart
= link_to 'Edit', edit_line_item_path(@line_item)
|
= link_to 'Back', line_items_path