config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :l_users
  resources :products do
  	get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts  
    root 'store#index', as: 'store_index', via: :all
  end


  post '/line_items/:id/update_quantity' => 'line_items#update_quantity', as: 'line_items_update_quantity'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title E-Commerce App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    :javascript
      I18n.defaultLocale = "#{I18n.default_locale}";
      I18n.locale= "#{I18n.locale}";

  %body
    %header.main
      %aside
        = form_tag store_index_path, class: 'locale' do
          = select_tag 'set_locale',                         |
            options_for_select(LANGUAGES, I18n.locale.to_s), |
            onchange: 'this.form.submit()'                   |
          = submit_tag 'submit', id: "submit_locale_change"
      
      = image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf'
      %h1= @page_title
    %section.content
      %nav.side_nav
        - if @cart
          #cart.carts
            = render_if @cart && @cart.line_items.any?, @cart
        %ul
          %li
            %a{:href => "/"}= t('.home')
          %li
            %a{:href => "/questions"}= t('.questions')
          %li
            %a{:href => "/news"}= t('.news')
          %li
            %a{:href => "/contact"}= t('.contact')

        - if session[:user_id]
          %nav.logged_in_nav
            %ul
              %li= link_to 'Orders', orders_path
              %li= link_to 'Products', products_path
              %li= link_to 'Users', l_users_path
              %li= button_to 'Logout', logout_path, method: :delete

      %main{:class => "#{controller.controller_name}"}
        = yield